jobs:
# Replace params / app_name with your heroku app name
- name: devops-app
  plan:
  - aggregate:
    - get: devops-app
    - get: devops-infra
  - task: mvn_build
    file: devops-infra/concourse/java/task.yml
    input_mapping: {source: devops-app}

  - task: push_to_heroku
    file: devops-infra/concourse/heroku/push_master_to_heroku.yml
    input_mapping: {source: devops-app}
    params:
      app_name: ((heroku_app_name))
      heroku_email: ((heroku_email))
      heroku_api_token: ((heroku_api_key))


- name: infra
  plan:
  - aggregate:
    - get: devops-infra
  - task: apply
    file: devops-infra/concourse/terraform/task.yml
    input_mapping: {source: devops-infra}
    params:
      github_token: ((github_token))
      heroku_api_key: ((heroku_api_key))
      statuscake_api_key: ((statuscake_api_key))
      command: apply
      directories: |
          terraform
  - put: devops-infra
    params:
      repository: with-state
      rebase: true

resources:

# Replace with your own repository
- name: devops-app
  type: git
  source:
      uri: git@github.com:anonexam/devops-app.git
      branch: master
      private_key: ((deploy_key_app))

# Replace with your own repository
- name: devops-infra
  type: git
  source:
      uri: git@github.com:anonexam/devops-infra.git
      branch: master
      private_key: ((deploy_key_infra))
